export const noteTemplates = {
  blank: {
    id: 'blank',
    name: 'Blank',
    description: 'Start with a clean canvas',
    category: 'General',
    color: '#6B7280',
    preview: '/templates/previews/blank.svg',
    elements: [],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#000000',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 20,
      currentItemTextAlign: 'left',
    },
    guideText: 'Start creating your note from scratch. Use the toolbar to add text, shapes, and drawings.'
  },
  
  cornell: {
    id: 'cornell',
    name: 'Cornell Notes',
    description: 'Structured note-taking with cues and summary',
    category: 'Cornell Notes',
    color: '#4F46E5',
    preview: '/templates/previews/cornell.svg',
    elements: [
      {
        type: 'rectangle',
        id: 'cornell-main',
        x: 50,
        y: 50,
        width: 700,
        height: 400,
        strokeColor: '#4F46E5',
        backgroundColor: 'transparent',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'rectangle',
        id: 'cornell-cues',
        x: 50,
        y: 50,
        width: 200,
        height: 400,
        strokeColor: '#4F46E5',
        backgroundColor: '#F0F9FF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'rectangle',
        id: 'cornell-summary',
        x: 50,
        y: 460,
        width: 700,
        height: 100,
        strokeColor: '#4F46E5',
        backgroundColor: '#F0F9FF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'cornell-title',
        x: 300,
        y: 30,
        width: 200,
        height: 20,
        text: 'Cornell Notes',
        fontSize: 24,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'cornell-cues-label',
        x: 100,
        y: 60,
        width: 100,
        height: 15,
        text: 'Cues',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#4F46E5',
      },
      {
        type: 'text',
        id: 'cornell-notes-label',
        x: 400,
        y: 60,
        width: 100,
        height: 15,
        text: 'Notes',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#4F46E5',
      },
      {
        type: 'text',
        id: 'cornell-summary-label',
        x: 400,
        y: 470,
        width: 100,
        height: 15,
        text: 'Summary',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#4F46E5',
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#4F46E5',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 16,
      currentItemTextAlign: 'left',
    },
    guideText: 'Cornell Notes: Use the left column for cues/questions, the right main area for detailed notes, and the bottom section for a summary of key points.'
  },
  
  mindmap: {
    id: 'mindmap',
    name: 'Mind Map',
    description: 'Visual brainstorming with connected ideas',
    category: 'Mind Map',
    color: '#7C3AED',
    preview: '/templates/previews/mindmap.svg',
    elements: [
      {
        type: 'ellipse',
        id: 'mindmap-center',
        x: 350,
        y: 250,
        width: 120,
        height: 60,
        strokeColor: '#7C3AED',
        backgroundColor: '#F3E8FF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'mindmap-center-text',
        x: 380,
        y: 275,
        width: 60,
        height: 15,
        text: 'Main Idea',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#7C3AED',
      },
      {
        type: 'ellipse',
        id: 'mindmap-branch-1',
        x: 150,
        y: 150,
        width: 100,
        height: 50,
        strokeColor: '#10B981',
        backgroundColor: '#D1FAE5',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'mindmap-branch-1-text',
        x: 175,
        y: 170,
        width: 50,
        height: 15,
        text: 'Topic 1',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#10B981',
      },
      {
        type: 'ellipse',
        id: 'mindmap-branch-2',
        x: 550,
        y: 150,
        width: 100,
        height: 50,
        strokeColor: '#F59E0B',
        backgroundColor: '#FEF3C7',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'mindmap-branch-2-text',
        x: 575,
        y: 170,
        width: 50,
        height: 15,
        text: 'Topic 2',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#F59E0B',
      },
      {
        type: 'ellipse',
        id: 'mindmap-branch-3',
        x: 150,
        y: 350,
        width: 100,
        height: 50,
        strokeColor: '#EF4444',
        backgroundColor: '#FEE2E2',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'mindmap-branch-3-text',
        x: 175,
        y: 370,
        width: 50,
        height: 15,
        text: 'Topic 3',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#EF4444',
      },
      {
        type: 'ellipse',
        id: 'mindmap-branch-4',
        x: 550,
        y: 350,
        width: 100,
        height: 50,
        strokeColor: '#3B82F6',
        backgroundColor: '#DBEAFE',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'mindmap-branch-4-text',
        x: 575,
        y: 370,
        width: 50,
        height: 15,
        text: 'Topic 4',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#3B82F6',
      },
      {
        type: 'arrow',
        id: 'mindmap-arrow-1',
        x: 270,
        y: 250,
        width: 80,
        height: 50,
        points: [[0, 0], [80, -50]],
        strokeColor: '#7C3AED',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'mindmap-arrow-2',
        x: 470,
        y: 250,
        width: 80,
        height: 50,
        points: [[0, 0], [80, -50]],
        strokeColor: '#7C3AED',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'mindmap-arrow-3',
        x: 270,
        y: 280,
        width: 80,
        height: 70,
        points: [[0, 0], [80, 70]],
        strokeColor: '#7C3AED',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'mindmap-arrow-4',
        x: 470,
        y: 280,
        width: 80,
        height: 70,
        points: [[0, 0], [80, 70]],
        strokeColor: '#7C3AED',
        strokeWidth: 2,
        roughness: 0,
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#7C3AED',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 14,
      currentItemTextAlign: 'center',
    },
    guideText: 'Mind Map: Start with your main idea in the center. Add related topics as branches and connect them with arrows. Use different colors to organize themes.'
  },
  
  flowchart: {
    id: 'flowchart',
    name: 'Flowchart',
    description: 'Process flow with decision points',
    category: 'Process',
    color: '#059669',
    preview: '/templates/previews/flowchart.svg',
    elements: [
      {
        type: 'rectangle',
        id: 'flow-start',
        x: 350,
        y: 50,
        width: 100,
        height: 40,
        strokeColor: '#059669',
        backgroundColor: '#D1FAE5',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-start-text',
        x: 380,
        y: 65,
        width: 40,
        height: 15,
        text: 'Start',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#059669',
      },
      {
        type: 'rectangle',
        id: 'flow-process-1',
        x: 350,
        y: 130,
        width: 100,
        height: 40,
        strokeColor: '#2563EB',
        backgroundColor: '#DBEAFE',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-process-1-text',
        x: 365,
        y: 145,
        width: 70,
        height: 15,
        text: 'Process 1',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#2563EB',
      },
      {
        type: 'diamond',
        id: 'flow-decision',
        x: 375,
        y: 210,
        width: 50,
        height: 50,
        strokeColor: '#DC2626',
        backgroundColor: '#FEE2E2',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-decision-text',
        x: 385,
        y: 230,
        width: 30,
        height: 15,
        text: '?',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#DC2626',
      },
      {
        type: 'rectangle',
        id: 'flow-process-2',
        x: 250,
        y: 290,
        width: 100,
        height: 40,
        strokeColor: '#2563EB',
        backgroundColor: '#DBEAFE',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-process-2-text',
        x: 265,
        y: 305,
        width: 70,
        height: 15,
        text: 'Process 2',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#2563EB',
      },
      {
        type: 'rectangle',
        id: 'flow-process-3',
        x: 450,
        y: 290,
        width: 100,
        height: 40,
        strokeColor: '#2563EB',
        backgroundColor: '#DBEAFE',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-process-3-text',
        x: 465,
        y: 305,
        width: 70,
        height: 15,
        text: 'Process 3',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#2563EB',
      },
      {
        type: 'rectangle',
        id: 'flow-end',
        x: 350,
        y: 370,
        width: 100,
        height: 40,
        strokeColor: '#059669',
        backgroundColor: '#D1FAE5',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-end-text',
        x: 380,
        y: 385,
        width: 40,
        height: 15,
        text: 'End',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#059669',
      },
      {
        type: 'arrow',
        id: 'flow-arrow-1',
        x: 400,
        y: 90,
        width: 0,
        height: 40,
        points: [[0, 0], [0, 40]],
        strokeColor: '#6B7280',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'flow-arrow-2',
        x: 400,
        y: 170,
        width: 0,
        height: 40,
        points: [[0, 0], [0, 40]],
        strokeColor: '#6B7280',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'flow-arrow-3',
        x: 375,
        y: 260,
        width: -50,
        height: 30,
        points: [[0, 0], [-50, 30]],
        strokeColor: '#6B7280',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'flow-arrow-4',
        x: 425,
        y: 260,
        width: 50,
        height: 30,
        points: [[0, 0], [50, 30]],
        strokeColor: '#6B7280',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'flow-arrow-5',
        x: 300,
        y: 330,
        width: 50,
        height: 40,
        points: [[0, 0], [50, 40]],
        strokeColor: '#6B7280',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'flow-arrow-6',
        x: 500,
        y: 330,
        width: -50,
        height: 40,
        points: [[0, 0], [-50, 40]],
        strokeColor: '#6B7280',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'flow-yes',
        x: 340,
        y: 275,
        width: 20,
        height: 12,
        text: 'Yes',
        fontSize: 12,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#059669',
      },
      {
        type: 'text',
        id: 'flow-no',
        x: 440,
        y: 275,
        width: 20,
        height: 12,
        text: 'No',
        fontSize: 12,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#DC2626',
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#2563EB',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 14,
      currentItemTextAlign: 'center',
    },
    guideText: 'Flowchart: Use rectangles for processes, diamonds for decisions, and arrows to show flow direction. Add "Yes/No" labels on decision branches.'
  },
  
  timeline: {
    id: 'timeline',
    name: 'Timeline',
    description: 'Chronological events and milestones',
    category: 'History',
    color: '#7C3AED',
    preview: '/templates/previews/timeline.svg',
    elements: [
      {
        type: 'line',
        id: 'timeline-main',
        x: 100,
        y: 250,
        width: 600,
        height: 0,
        points: [[0, 0], [600, 0]],
        strokeColor: '#7C3AED',
        strokeWidth: 3,
        roughness: 0,
      },
      {
        type: 'ellipse',
        id: 'timeline-point-1',
        x: 150,
        y: 250,
        width: 20,
        height: 20,
        strokeColor: '#7C3AED',
        backgroundColor: '#7C3AED',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'ellipse',
        id: 'timeline-point-2',
        x: 300,
        y: 250,
        width: 20,
        height: 20,
        strokeColor: '#7C3AED',
        backgroundColor: '#7C3AED',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'ellipse',
        id: 'timeline-point-3',
        x: 450,
        y: 250,
        width: 20,
        height: 20,
        strokeColor: '#7C3AED',
        backgroundColor: '#7C3AED',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'ellipse',
        id: 'timeline-point-4',
        x: 600,
        y: 250,
        width: 20,
        height: 20,
        strokeColor: '#7C3AED',
        backgroundColor: '#7C3AED',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'rectangle',
        id: 'timeline-event-1',
        x: 100,
        y: 150,
        width: 100,
        height: 60,
        strokeColor: '#10B981',
        backgroundColor: '#D1FAE5',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'timeline-event-1-text',
        x: 120,
        y: 175,
        width: 60,
        height: 15,
        text: 'Event 1',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#10B981',
      },
      {
        type: 'text',
        id: 'timeline-date-1',
        x: 120,
        y: 195,
        width: 60,
        height: 12,
        text: 'Date 1',
        fontSize: 12,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#6B7280',
      },
      {
        type: 'rectangle',
        id: 'timeline-event-2',
        x: 250,
        y: 320,
        width: 100,
        height: 60,
        strokeColor: '#F59E0B',
        backgroundColor: '#FEF3C7',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'timeline-event-2-text',
        x: 270,
        y: 345,
        width: 60,
        height: 15,
        text: 'Event 2',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#F59E0B',
      },
      {
        type: 'text',
        id: 'timeline-date-2',
        x: 270,
        y: 365,
        width: 60,
        height: 12,
        text: 'Date 2',
        fontSize: 12,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#6B7280',
      },
      {
        type: 'rectangle',
        id: 'timeline-event-3',
        x: 400,
        y: 150,
        width: 100,
        height: 60,
        strokeColor: '#EF4444',
        backgroundColor: '#FEE2E2',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'timeline-event-3-text',
        x: 420,
        y: 175,
        width: 60,
        height: 15,
        text: 'Event 3',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#EF4444',
      },
      {
        type: 'text',
        id: 'timeline-date-3',
        x: 420,
        y: 195,
        width: 60,
        height: 12,
        text: 'Date 3',
        fontSize: 12,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#6B7280',
      },
      {
        type: 'rectangle',
        id: 'timeline-event-4',
        x: 550,
        y: 320,
        width: 100,
        height: 60,
        strokeColor: '#3B82F6',
        backgroundColor: '#DBEAFE',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'timeline-event-4-text',
        x: 570,
        y: 345,
        width: 60,
        height: 15,
        text: 'Event 4',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#3B82F6',
      },
      {
        type: 'text',
        id: 'timeline-date-4',
        x: 570,
        y: 365,
        width: 60,
        height: 12,
        text: 'Date 4',
        fontSize: 12,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#6B7280',
      },
      {
        type: 'arrow',
        id: 'timeline-arrow-1',
        x: 160,
        y: 210,
        width: 0,
        height: 40,
        points: [[0, 0], [0, 40]],
        strokeColor: '#10B981',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'timeline-arrow-2',
        x: 310,
        y: 320,
        width: 0,
        height: -70,
        points: [[0, 0], [0, -70]],
        strokeColor: '#F59E0B',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'timeline-arrow-3',
        x: 460,
        y: 210,
        width: 0,
        height: 40,
        points: [[0, 0], [0, 40]],
        strokeColor: '#EF4444',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'arrow',
        id: 'timeline-arrow-4',
        x: 610,
        y: 320,
        width: 0,
        height: -70,
        points: [[0, 0], [0, -70]],
        strokeColor: '#3B82F6',
        strokeWidth: 2,
        roughness: 0,
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#7C3AED',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 14,
      currentItemTextAlign: 'center',
    },
    guideText: 'Timeline: Place events along the main timeline. Use alternating positions (above/below) for better readability. Include dates and descriptions for each milestone.'
  },
  
  comparison: {
    id: 'comparison',
    name: 'Comparison',
    description: 'Side-by-side comparison of topics',
    category: 'Analysis',
    color: '#3B82F6',
    preview: '/templates/previews/comparison.svg',
    elements: [
      {
        type: 'rectangle',
        id: 'comparison-left',
        x: 50,
        y: 100,
        width: 300,
        height: 400,
        strokeColor: '#3B82F6',
        backgroundColor: '#EFF6FF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'rectangle',
        id: 'comparison-right',
        x: 450,
        y: 100,
        width: 300,
        height: 400,
        strokeColor: '#10B981',
        backgroundColor: '#F0FDF4',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'comparison-title',
        x: 300,
        y: 50,
        width: 200,
        height: 20,
        text: 'Comparison',
        fontSize: 24,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'comparison-left-title',
        x: 200,
        y: 120,
        width: 100,
        height: 20,
        text: 'Topic A',
        fontSize: 18,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#3B82F6',
      },
      {
        type: 'text',
        id: 'comparison-right-title',
        x: 600,
        y: 120,
        width: 100,
        height: 20,
        text: 'Topic B',
        fontSize: 18,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'top',
        strokeColor: '#10B981',
      },
      {
        type: 'text',
        id: 'comparison-left-point-1',
        x: 70,
        y: 180,
        width: 260,
        height: 15,
        text: '• Point 1 for Topic A',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'comparison-left-point-2',
        x: 70,
        y: 220,
        width: 260,
        height: 15,
        text: '• Point 2 for Topic A',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'comparison-left-point-3',
        x: 70,
        y: 260,
        width: 260,
        height: 15,
        text: '• Point 3 for Topic A',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'comparison-right-point-1',
        x: 470,
        y: 180,
        width: 260,
        height: 15,
        text: '• Point 1 for Topic B',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'comparison-right-point-2',
        x: 470,
        y: 220,
        width: 260,
        height: 15,
        text: '• Point 2 for Topic B',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'text',
        id: 'comparison-right-point-3',
        x: 470,
        y: 260,
        width: 260,
        height: 15,
        text: '• Point 3 for Topic B',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#1F2937',
      },
      {
        type: 'rectangle',
        id: 'comparison-vs',
        x: 375,
        y: 280,
        width: 50,
        height: 40,
        strokeColor: '#7C3AED',
        backgroundColor: '#F3E8FF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'comparison-vs-text',
        x: 390,
        y: 295,
        width: 20,
        height: 15,
        text: 'VS',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#7C3AED',
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#3B82F6',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 14,
      currentItemTextAlign: 'left',
    },
    guideText: 'Comparison: Use the left and right columns to compare two topics. List key points for each side. The center "VS" highlights the comparison nature.'
  },

  studyGuide: {
    id: 'studyGuide',
    name: 'Study Guide',
    description: 'Key concepts, vocabulary, and review questions',
    category: 'Study Guide',
    color: '#F59E0B',
    preview: '/templates/previews/study-guide.svg',
    elements: [
      {
        type: 'rectangle',
        id: 'sg-header',
        x: 50,
        y: 30,
        width: 700,
        height: 50,
        strokeColor: '#F59E0B',
        backgroundColor: '#FEF3C7',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'sg-title',
        x: 350,
        y: 45,
        width: 100,
        height: 20,
        text: 'Study Guide',
        fontSize: 22,
        fontFamily: 1,
        textAlign: 'center',
        verticalAlign: 'middle',
        strokeColor: '#F59E0B',
      },
      {
        type: 'rectangle',
        id: 'sg-concepts',
        x: 50,
        y: 100,
        width: 700,
        height: 140,
        strokeColor: '#F59E0B',
        backgroundColor: 'transparent',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'sg-concepts-label',
        x: 70,
        y: 110,
        width: 120,
        height: 18,
        text: 'Key Concepts',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#F59E0B',
      },
      {
        type: 'rectangle',
        id: 'sg-vocab',
        x: 50,
        y: 260,
        width: 700,
        height: 140,
        strokeColor: '#F59E0B',
        backgroundColor: 'transparent',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'sg-vocab-label',
        x: 70,
        y: 270,
        width: 100,
        height: 18,
        text: 'Vocabulary',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#F59E0B',
      },
      {
        type: 'rectangle',
        id: 'sg-questions',
        x: 50,
        y: 420,
        width: 700,
        height: 140,
        strokeColor: '#F59E0B',
        backgroundColor: 'transparent',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'sg-questions-label',
        x: 70,
        y: 430,
        width: 140,
        height: 18,
        text: 'Review Questions',
        fontSize: 16,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'top',
        strokeColor: '#F59E0B',
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#F59E0B',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 14,
      currentItemTextAlign: 'left',
    },
    guideText: 'Study Guide: Use Key Concepts for main ideas, Vocabulary for terms and definitions, and Review Questions to test your understanding.'
  },

  flashcardSet: {
    id: 'flashcardSet',
    name: 'Flashcard Set',
    description: 'Q&A cards for review and memorization',
    category: 'Flashcard Set',
    color: '#EC4899',
    preview: '/templates/previews/flashcard-set.svg',
    elements: [
      {
        type: 'rectangle',
        id: 'fc1-front',
        x: 80,
        y: 80,
        width: 200,
        height: 100,
        strokeColor: '#EC4899',
        backgroundColor: '#FFFFFF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'fc1-q',
        x: 100,
        y: 115,
        width: 160,
        height: 24,
        text: 'Q: Your question here',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'middle',
        strokeColor: '#EC4899',
      },
      {
        type: 'rectangle',
        id: 'fc1-back',
        x: 100,
        y: 100,
        width: 200,
        height: 100,
        strokeColor: '#EC4899',
        backgroundColor: '#FCE7F3',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'fc1-a',
        x: 120,
        y: 135,
        width: 160,
        height: 24,
        text: 'A: Your answer here',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'middle',
        strokeColor: '#EC4899',
      },
      {
        type: 'rectangle',
        id: 'fc2-front',
        x: 320,
        y: 220,
        width: 200,
        height: 100,
        strokeColor: '#EC4899',
        backgroundColor: '#FFFFFF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'fc2-q',
        x: 340,
        y: 255,
        width: 160,
        height: 24,
        text: 'Q: Your question here',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'middle',
        strokeColor: '#EC4899',
      },
      {
        type: 'rectangle',
        id: 'fc2-back',
        x: 340,
        y: 240,
        width: 200,
        height: 100,
        strokeColor: '#EC4899',
        backgroundColor: '#FCE7F3',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'fc2-a',
        x: 360,
        y: 275,
        width: 160,
        height: 24,
        text: 'A: Your answer here',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'middle',
        strokeColor: '#EC4899',
      },
      {
        type: 'rectangle',
        id: 'fc3-front',
        x: 80,
        y: 360,
        width: 200,
        height: 100,
        strokeColor: '#EC4899',
        backgroundColor: '#FFFFFF',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'fc3-q',
        x: 100,
        y: 395,
        width: 160,
        height: 24,
        text: 'Q: Your question here',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'middle',
        strokeColor: '#EC4899',
      },
      {
        type: 'rectangle',
        id: 'fc3-back',
        x: 100,
        y: 380,
        width: 200,
        height: 100,
        strokeColor: '#EC4899',
        backgroundColor: '#FCE7F3',
        fillStyle: 'solid',
        strokeWidth: 2,
        roughness: 0,
      },
      {
        type: 'text',
        id: 'fc3-a',
        x: 120,
        y: 415,
        width: 160,
        height: 24,
        text: 'A: Your answer here',
        fontSize: 14,
        fontFamily: 1,
        textAlign: 'left',
        verticalAlign: 'middle',
        strokeColor: '#EC4899',
      },
    ],
    appState: {
      viewBackgroundColor: '#ffffff',
      currentItemStrokeColor: '#EC4899',
      currentItemBackgroundColor: '#ffffff',
      currentItemFontFamily: 1,
      currentItemFontSize: 14,
      currentItemTextAlign: 'left',
    },
    guideText: 'Flashcard Set: Use each card pair for a question (Q:) and answer (A:). Duplicate or add more cards as needed for your study set.'
  }
};

export const getTemplateById = (id) => {
  return noteTemplates[id] || noteTemplates.blank;
};

export const getTemplateList = () => {
  return Object.values(noteTemplates);
};
